name: "Application Name"
description: "Application description"

development:
  host: "localhost"
  asset_host: "localhost"

test:
  host: "localhost"
  asset_host: "localhost"

staging:
  host: "localhost"
  asset_host: "localhost"

production:
  host: "localhost"
  asset_host: "localhost"